### ISSUE TITLE
Rewrite table-js with focus on performance

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/table-js#10]
table-js performs poorly when dealing with >500 rows which sometimes is required. This is due to the core architecture of the library which was not designed with performance in mind. Therefore a rewrite of the library is more promising than trying to tweak the current architecture for better performance.

**Comment by nikku** [comment]
:rocket:

**Comment by nikku** [comment]
Instead of releasing patch versions of the un-released major, what about releasing pre-release versions instead? `1.0.0-0 > 1.0.0-1`?

**Comment by nikku** [comment]
Should work via `np pre-major`, too.
